name: remote ssh command

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 118.96.36.173
        username: u0_a116
        password: 134645
        #key: ${{ secrets.SSH}}
        port: 22
        script: |
          cd ~/html
          git pull origin master
          git status
